version: "1.0"
services:
  blog:
    image: nginx:1.21.0
    container_name: blog-nginx
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html # 挂载当前静态网页文件目录
      - ./nginx/default.conf:/ /etc/nginx/conf.d/default.conf # 挂载 Nginx 配置文件
      - ./cert:/etc/nginx/cert # 挂载 SSL 证书目录
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=mango-reader.cn
      - NGINX_HOST_SSL_CRT=cert/mango-reader.cn/fullchain.pem
      - NGINX_HOST_SSL_KEY=cert/mango-reader.cn/privkey.pem